CREATE DATABASE IF NOT EXISTS pet_care_db DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE pet_care_db;

CREATE TABLE IF NOT EXISTS users (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    contact VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pet_name VARCHAR(100) NOT NULL,
    categories VARCHAR(100) NOT NULL,
    vet VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS appointments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pet_name VARCHAR(100) NOT NULL,
    clinic VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS care_routines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pet_name VARCHAR(100) NOT NULL,
    routine_type VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    notes TEXT
);